### ISSUE TITLE
Crafting gears might be impossible

### ISSUE THREAD

**Issue by opl-** [general-programming/mc-xmas-2018#7]
Something something cba to write proper description.

Might be possible to craft the first gear through Immersive Engineering, but even then it sounds unintended.

**Comment by hedgehog1029** [comment]
it's intentional - you can craft wooden and stone gears, which you then upgrade to iron via botania, and transmute iron gears to copper and tin gears via astral, which is enough to allow you to make a compactor with the gear die augment OR make the Tinkers gear cast

...I didn't fully test the compactor route, but I'm 99% sure the Tinkers route works

**Comment by opl-** [comment]
It does work, it's actually how we ended up doing it.
